### ISSUE TITLE
Duplicate components generated

### ISSUE THREAD

**Issue by braco** [kota65535/openapi-merger#30]
If we have a spec like this:

```
components:
  schemas:
    FooBar:
      $ref: "schemas/Foo/Bar.yml"
```

this package will generate duplicate schemas: `FooBar` and `Bar`. It seems like the correct behavior would be deferring to the chosen name `FooBar` and not creating `Bar`, especially since you're dropping folder structure.

Excellent start to this package by the way! I tried about 20 different OAPI generating frameworks today.
