### ISSUE TITLE
Needs different merge strategy

### ISSUE THREAD

**Issue by braco** [kota65535/openapi-merger#31]
Common.yml
```
properties:
  things:
    type: object
    properties:
        foo: ...
        bar: ...
```

Extended.yml
```
$include: "./Common.yml"
description: ...
properties:
  types: ...
  tags: ...
  things:
    properties:
        baz: ...
        boo: ...
 ```

The intention here is that Common.yml has some `things` that are merged with Extended.yml. However, the merge strategy isn't deep, so Extended overwrites everything in Common, yielding only baz and boo.

edit: this seems like it may be a bug since two includes:
```
$include#1: ...
$include#2: ...
```
seem to merge deeply, but not include and an inline object.
